#!/usr/bin/bash

# Author: Fang
# Date: 2020/02/17

# Don't add code before the initialization
#region Initialization DO NOT TOUCH
# Interactive mode initialization script
# Prevent from being loaded twice
if [ -z "$INIT_SH_LOADED" ]; then
    INIT_SH_LOADED=1
else
    return
fi
# If in non-interactive mode then exit
case "$-" in
    *i*) ;;
    *) return
esac

_rcroot=$(dirname $(realpath $BASH_SOURCE))


source "$_rcroot/rcore"
#region My code
loadmodule "$_rcroot/modules" aliases
loadmodule "$_rcroot/bash_prompts" mybash
#endregion
