#!/bin/sh
exec tail -n +3 $0
### Ver 1.2 ###
#################################################################
insmod part_gpt
insmod part_msdos
terminal_input console
terminal_output gfxterm
set imagedir="/boot/image/"
set timeout=30
set default=0

menuentry "Arch Linux dual 2016.09.03" {
	set imagefile="${imagedir}archlinux-2016.09.03-dual.iso"
	search --no-floppy --set=imgdisk --file ${imagefile} 
	probe --set=diskuuid --fs-uuid ${imgdisk}
	loopback loop ${imagefile}
	linux (loop)/arch/boot/x86_64/vmlinuz img_dev="/dev/disk/by-uuid/${diskuuid}" img_loop=${imagefile} earlymodules=loop
	initrd (loop)/arch/boot/x86_64/archiso.img
}

menuentry "Ubuntu Desktop amd64 16.04.1" {
	set imagefile="${imagedir}ubuntu-16.04.1-desktop-amd64.iso"
	loopback loop ${imagefile}
	linux (loop)/casper/vmlinuz.efi boot=casper iso-scan/filename=${imagefile} noprompt noeject toram --
	initrd (loop)/casper/initrd.lz
}

menuentry "Restart" {
	echo "Restarting computer..."
	reboot
}
menuentry "Shutdown" {
	echo "Shuting down..."
	halt
}