" Rc file root directory
let s:rcroot = fnamemodify(resolve(expand('<sfile>:p')), ':h')

" Dynamically load .vim files
function! s:loadvim(path) abort
    for m in split(glob(a:path . "/*.vim"), "\n")
        execute "source" m
    endfor
endfunction

" Load customized configs
call s:loadvim(s:rcroot . "/confs")
