#!/usr/bin/bash

# Author: Fang
# Date: 2020/02/17

# Don't add code before the initialization
# Interactive mode initialization script
# Prevent from being loaded twice
if [ -z "$INIT_SH_LOADED" ]; then
    INIT_SH_LOADED=1
else
    return
fi
# If in non-interactive mode then exit
case "$-" in
    *i*) ;;
    *) return
esac

# This rc script
_rcroot=$(dirname $(realpath $BASH_SOURCE))
# Load core module
_saved_cwd=$(pwd)
cd "$_rcroot/../shell"
source ./shellrc
source ./profile
cd $_saved_cwd
# Load prompt style
if [ -z "$1" ]; then
    loadmodule "$_rcroot/prompts" mybash
else
    loadmodule "$_rcroot/prompts" "$1"
fi

# Clean up
unset _saved_cwd
unset _rcroot
