#!/usr/bin/bash

# Author: Fang
# Date: 2020/02/17

# Don't add code before the initialization
# Interactive mode initialization script
# Prevent from being loaded twice
if [ -z "$INIT_SH_LOADED" ]; then
    INIT_SH_LOADED=1
else
    return
fi
# If in non-interactive mode then exit
case "$-" in
    *i*) ;;
    *) return
esac

# This rc script
_rcroot=$(dirname $(realpath $BASH_SOURCE))
# Load core module
source "$_rcroot/../shell/rcore.shm"
# Load modules
loadmodule "$_rcroot/../shell/modules" aliases
loadmodule "$_rcroot/prompts" mybash
